# Generated by Django 3.1.12 on 2021-06-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20)),
                ('m_name', models.CharField(max_length=10)),
                ('l_name', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=7)),
                ('nationality', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('pin_code', models.CharField(max_length=6)),
                ('qualification', models.CharField(max_length=15)),
                ('salary', models.CharField(max_length=10)),
                ('pan', models.CharField(max_length=15)),
            ],
        ),
    ]
