# Generated by Django 3.1.12 on 2021-06-30 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='dob',
            new_name='DOB',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='pan',
            new_name='PAN',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='l_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='m_name',
            new_name='middle_name',
        ),
    ]
