# Generated by Django 3.1.12 on 2021-06-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20210630_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='PAN',
            field=models.CharField(max_length=10),
        ),
    ]
